site_name: Rajiv Kumar
site_url: https://krajiv.github.io/profile/
theme:
  name: material
  logo: assets/images/favicon.png
  palette:
    primary: blue
nav:
 - Home: index.md
 - Certifications:
     - Leadership:
         - Executive Decision Making: certificates/leadership/page/edm.md
         - Leading Effectively: certificates/leadership/page/le.md
         - Solving Business Problems: certificates/leadership/page/sbp.md
     - Product Management:
         - Creating a Product Centric Organization: certificates/pm/page/capco.md
         - Productization Essentials for Engg. Leaders: certificates/pm/page/pe.md
         - Decision Making Strategies: certificates/pm/page/dms.md
         - Pitching Product to Executives: certificates/pm/page/p2e.md
         - Product Management: certificates/pm/page/pmfs.md
     - Marketing:
         - Create a Go-To-Market Plan: certificates/marketing/page/cagtmp.md
         - Market Research: certificates/marketing/page/mfmr.md
     - Data Science:
         - The Data Scientist Toolbox: certificates/data-science/page/tdst.md
         - R Programming: certificates/data-science/page/rprog.md
         - Getting and Cleaning Data: certificates/data-science/page/gacd.md
 - Presentations:
     - Permission Collection service: ppt/pcrs.md
     - Novell Identity Manager Troubleshooting: ppt/idm.md
 - Posts:
     - Decentralized Identity: posts/dim.md
 - About: about.md
